import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Employee Content Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Manager's Dashboard
        </h1>

        <p className={styles.description}>
          Hello{' '}
          <code className={styles.code}>Placeholder</code>
        </p>

        <div className={styles.grid}>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Snapshots</h2>
            <p>Employees &rarr;</p>
            <p>Roles &rarr;</p>
            <p>Departments &rarr;</p>
          </a>

          <div className={styles.card}>
            <h2>Add</h2>
            <a href="/new-employee">New Employee &rarr;</a>
            <p>New Role &rarr;</p>
            <p>New Department &rarr;</p>
          </div>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}>
            <h2>Update Employee</h2>
            <p>Role &rarr;</p>
            <p>Manager &rarr;</p>
            <p>Remove &rarr;</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Budget &rarr;</h2>
            <p>Total</p>
            <p>By Department</p>
            <p>By Manager</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
